decrypt: {npmrc: repo/npmrc.asc}
release:
  script: |-
    npm install
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --userconfig=../npmrc
architect: [yegor256, yegor256, davvd]