decrypt:
  npmrc: repo/npmrc.asc
install: |
  npm install
release:
  script: |-
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --userconfig=../npmrc
  commanders:
  - yegor256
architect:
- yegor256
- davvd
merge:
  commanders: []
  script: npm test
deploy:
  script: npm test