decrypt:
  npmrc: "repo/npmrc.asc"

release:
  script: |
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    npm --userconfig=./npmrc publish . dynamo-archive@${tag}
    npm --userconfig=./npmrc tag dynamo-archive@${tag} latest
