decrypt:
  npmrc: "repo/npmrc.asc"

release:
  script: |
    sudo ln -s /usr/bin/nodejs /usr/bin/node
    npm install
    npm test
    sed -i "s/0.0.0/${tag}/g" package.json
    chmod 600 ../npmrc
    npm publish --userconfig=../npmrc
